var filenameArea = document.getElementById("filename");
var downloadDiv = document.getElementById("downloadDiv");
var defaultModal = document.getElementById("defaultValueModal");
var maxModal = document.getElementById("maxValueModal");
var minModal = document.getElementById("minValueModal");
var randomModal = document.getElementById("randomValueModal");
var closeDefaultBtn = document.getElementsByClassName("close")[0];
var closeMaxBtn = document.getElementsByClassName("close")[1];
var closeMinBtn = document.getElementsByClassName("close")[2];
var closeRandomBtn = document.getElementsByClassName("close")[3];
var fileExtension;
var oldFilename;
var isShiftDown = false;
var codeEditor = document.getElementById("codeEditor");
var insertDefault = document.getElementById("insertdefaultBtn");
var insertMax = document.getElementById("insertmaxBtn");
var insertMin = document.getElementById("insertminBtn");
var insertRandom = document.getElementById("insertrandomBtn");
var defaultDataTypeSelect = document.getElementById('defaultDataTypeSelect');
var maxDataTypeSelect = document.getElementById('maxDataTypeSelect');
var minDataTypeSelect = document.getElementById('minDataTypeSelect');
var randomDataTypeSelect = document.getElementById('randomDataTypeSelect');
